/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#ffb693",
        "on-primary": "#561f00",
        "on-error-container": "#ffdad6",
        "on-tertiary-container": "#00373e",
        "inverse-primary": "#a04100",
        "on-secondary-fixed-variant": "#574500",
        "on-surface-variant": "#e2bfb0",
        "inverse-surface": "#e5e2e1",
        "outline-variant": "#5a4136",
        "surface-container-high": "#2a2a2a",
        "surface-container-lowest": "#0e0e0e",
        "secondary-fixed-dim": "#e9c349",
        "background": "#0a0a0a",
        "secondary-fixed": "#ffe088",
        "on-tertiary": "#00363d",
        "secondary-container": "#af8d11",
        "error-container": "#93000a",
        "on-primary-fixed": "#351000",
        "on-secondary": "#3c2f00",
        "surface-container-low": "#1c1b1b",
        "tertiary-fixed": "#9cf0ff",
        "surface": "#131313",
        "surface-bright": "#3a3939",
        "surface-container-highest": "#353534",
        "error": "#ffb4ab",
        "tertiary": "#00daf3",
        "on-primary-container": "#572000",
        "on-secondary-container": "#342800",
        "on-primary-fixed-variant": "#7a3000",
        "tertiary-container": "#00a8bb",
        "surface-tint": "#ffb693",
        "on-tertiary-fixed": "#001f24",
        "surface-dim": "#131313",
        "surface-variant": "#353534",
        "on-surface": "#e5e2e1",
        "on-error": "#690005",
        "outline": "#a98a7d",
        "surface-container": "#201f1f",
        "tertiary-fixed-dim": "#00daf3",
        "on-background": "#e5e2e1",
        "on-tertiary-fixed-variant": "#004f58",
        "primary-container": "#ff6b00",
        "primary-fixed": "#ffdbcc",
        "inverse-on-surface": "#313030",
        "on-secondary-fixed": "#241a00",
        "secondary": "#e9c349",
        "primary-fixed-dim": "#ffb693"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "8px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        "container-max": "1440px",
        "gutter": "24px"
      },
      fontFamily: {
        "label-caps": ["Space Grotesk", "sans-serif"],
        "display-lg-mobile": ["Anybody", "sans-serif"],
        "headline-xl-mobile": ["Anybody", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-xl": ["Anybody", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Anybody", "sans-serif"],
        "label-mono": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Anybody", "sans-serif"]
      }
    },
  },
  plugins: [],
}
